repos:
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    - id: black
      language_version: python3.9.2
      exclude: migrations/
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
