# Generated by Django 4.1.3 on 2022-11-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CTFLog', '0003_campaign_slug_ctf_slug_site_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
